#!/bin/sh
#
# chkconfig: - 91 35
# description: Starts and stops the Samba smbd and nmbd daemons \
#            used to provide SMB network services.
#
# pidfile: /var/run/samba/smbd.pid
# pidfile: /var/run/samba/nmbd.pid
# config:  /etc/samba/smb.conf



# Source function library.
if [ -f /etc/init.d/functions ] ; then
  . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
  . /etc/rc.d/init.d/functions
else
  exit 1
fi

# Avoid using root's TMPDIR
unset TMPDIR

# Source networking configuration.
. /etc/sysconfig/network

#export LD_LIBRARY_PATH=/usr/local/samba/lib:$LD_LIBRARY_PATH
#export LD_PRELOAD="/usr/local/samba/lib/libtdb.so.1"

SMBDOPTIONS="-D"
NMBDOPTIONS="-D"
WINBINDOPTIONS="-D"

SMBD=/usr/local/samba/sbin/smbd
NMBD=/usr/local/samba/sbin/nmbd
WINBINDD=/usr/local/samba/sbin/winbindd

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 1

# Check that smb.conf exists.
#[ -f /etc/samba/smb.conf ] || exit 6

RETVAL=0


start() {
     echo -n $"Starting $(basename $SMBD) services: "
     daemon $SMBD $SMBDOPTIONS
     RETVAL=$?
     echo

     echo -n $"Starting $(basename $NMBD) services: "
     daemon $NMBD $NMBDOPTIONS
     RETVAL2=$?
     echo

     echo -n $"Starting $(basename $WINBINDD) services: "
     daemon $WINBINDD $WINBINDOPTIONS
     RETVAL3=$?
     echo

     [ $RETVAL -eq 0 -a $RETVAL3 -eq 0 ] && touch /var/lock/subsys/smb || \
        RETVAL=1
     return $RETVAL
}    

stop() {
     echo -n $"Shutting down $(basename $SMBD) services: "
     killproc $(basename $SMBD)
     RETVAL=$?
     echo

     echo -n $"Shutting down $(basename $NMBD) services: "
     killproc $(basename $NMBD)
     RETVAL2=$?
     echo

     echo -n $"Shutting down $(basename $WINBINDD) services: "
     killproc $(basename $WINBINDD)
     RETVAL3=$?
     echo

     [ $RETVAL -eq 0 -a $RETVAL3 -eq 0 ] && rm -f /var/lock/subsys/smb
     return $RETVAL
}

restart() {
     stop
     start
}    

reload() {
     kill -HUP `pidof smbd`
}

rhstatus() {
     status $(basename $SMBD)
     RETVAL=$?
     status $(basename $NMBD)
     RETVAL2=$?
     status $(basename $WINBINDD)
     RETVAL3=$?

     if [ $RETVAL -ne 0 ] ; then
          return $RETVAL
     fi
     if [ $RETVAL2 -ne 0 ] ; then
          return $RETVAL2
     fi
     if [ $RETVAL3 -ne 0 ] ; then
          return $RETVAL3
     fi
}    


# Allow status as non-root.
if [ "$1" = status ]; then
       rhstatus
       exit $?
fi

# Check that we can write to it... so non-root users stop here
#[ -w /etc/samba/smb.conf ] || exit 4


case "$1" in
  start)
       start
     ;;
  stop)
       stop
     ;;
  restart)
       restart
     ;;
  reload)
       reload
     ;;
  status)
       rhstatus
     ;;
  condrestart)
       [ -f /var/lock/subsys/smb ] && restart || :
     ;;
  *)
     echo $"Usage: $0 {start|stop|restart|reload|status|condrestart}"
     exit 2
esac

exit $?
